[package]
name = "alos"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["macros"]

[target.x86_64-unknown-none]
rustflags = ["-C", "target-feature=-mmx", "-C", "target-feature=-sse"]

[profile.dev]
opt-level = 1

[features]
default = []
smp = []

[dependencies]
macros = { path = "macros" }
limine = "0.5.0"
spin = "0.12.3"
paste = "1.0.15"
acpi = "6.0.1"
elf = { version = "0.8.0", default-features = false, features = ["alloc"] }
elf_loader = { version = "0.17.0", default-features = false, features = [] }
bytemuck = "1.25.2"
